Update Automated_change_process.yml

diff --git a/.github/workflows/Automated_change_process.yml b/.github/workflows/Automated_change_process.yml
--- a/.github/workflows/Automated_change_process.yml
+++ b/.github/workflows/Automated_change_process.yml
@@ -23,7 +23,7 @@ jobs:
         export CHANGE_TYPE="Code Push"
         
         export DATA='{
-          "short_description": "Automated Change Request from GitHub Actions - Testing3",
+          "short_description": "Automated Change Request from GitHub Actions - Testing4",
           "description": "'"$CHANGE_TYPE"' in GitHub repository \n '"$GITHUB_REPOSITORY"' \n '"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$GITHUB_REF"'"
         }'
 
@@ -34,12 +34,17 @@ jobs:
         --data "$DATA" \
         --fail || echo "Failed to create change request"
 
-        # Extract sys_id from the response and save to a file
+        # Output the full response for debugging
+        echo "Response: $RESPONSE"
+
+        # Extract sys_id from the response using jq
         SYS_ID=$(echo $RESPONSE | jq -r '.result.sys_id')
-        if [ -z "$SYS_ID" ] || [ "$SYS_ID" == "null" ]; then
-          echo "Failed to retrieve sys_id. Response: $RESPONSE"
-          exit 1
+
+        # Validate if sys_id is successfully retrieved
+        if [ -n "$SYS_ID" ] && [ "$SYS_ID" != "null" ]; then
+            echo "Successfully created change request with sys_id: $SYS_ID"
+            echo "$SYS_ID" > change_request_sys_id.txt
         else
-          echo "Successfully created change request with sys_id: $SYS_ID"
-          echo "$SYS_ID" > change_request_sys_id.txt
+            echo "Failed to retrieve sys_id. Response: $RESPONSE"
+            exit 1
         fi
